### ISSUE TITLE
Windows Image paths not fully escaped

### ISSUE THREAD

**Issue by xavigu42** [SigmaHQ/pySigma-backend-crowdstrike#17]
Hi guys,

The Windows path is not fully escaped in `Image` selectors but it seems to be fine for `CommandLine`

Example:
https://github.com/SigmaHQ/sigma/blob/598d29f811c1859ba18e05b8c419cc94410c9a55/rules/windows/process_creation/proc_creation_win_susp_execution_path.yml#L23

Expected:

```
ImageFileName=/:\\Users\\All Users\\/i
```

Current output:
```
ImageFileName=/\\Users\\All Users\/i
```

The path is escaped correctly if we replace `Image` with `CommandLine`

```
detection:
    selection:
        CommandLine|contains:
            - ':\Perflogs\'
            - ':\Users\All Users\'
```

**Comment by moullos** [comment]
Hi @thomaspatzke 

I might need your help again. The behavior outlined by @xavigu42 changes for the latest version of pysigma (0.11.14) but is still problematic. The below condition:

```
Image|contains: /:\Users\All Users\
```
results to:
```
ImageFileName=/\\Users\\All Users\*$/i
```
expected output would be:
```
ImageFileName=/\\Users\\All Users\\/i
```
The behaviour is only present when the following conditions are met:
 - The field has the "contains" modifier applied
 - The value ends in a backslash
 - The field goes through a ReplaceStringTransformation

I believe that the combination of the backlash + the '\*' added from the contains leads to the backlash not being properly escaped by the ReplaceStringTransformation (SigmaHQ/pysigma#273). As a result, it's getting handled as a literal match to the character '*' due to the \\\* combination in the SigmaString.

**Comment by thomaspatzke** [comment]
Reproduced in pySigma, fixing it there.

**Comment by thomaspatzke** [comment]
Ok, that's a really tricky one. The `contains` modifier adds wildcards around the value. The observed behavior can be mitigated by enabling the `skip_special` option of `ReplaceStringTransformation`. This leads into the next issue with `cql_imagefilename_replace_disk_name` where the replacement value introduces a new `?` wildcard that is intended to be interpreted but isn't in the current implementation if `skip_special` is `True`.

Depending on the use case both behaviors can be valid. Therefore, I add an additional option `interpret_special` in the transformation and enable it in the transformation.

**Comment by thomaspatzke** [comment]
Just releasing v2.0.1
